version: '3.9'
services:
  app:
    container_name: recipe-search-app
    build: .
    context: .
    dockerfile: Dockerfile
    depends_on:
      - postgres
    restart: always
    environment:
        PORT: {PORT}
        DB_HOST: {DB_HOST}
        JWT_SECRET: {JWT_SECRET}
        DB_PORT: {DB_PORT}
        DB_USERNAME: {DB_USERNAME}
        GITHUB_TOKEN: {GITHUB_TOKEN}
        GH_AI_ENDPOINT: {GH_AI_ENDPOINT}
        GH_AI_MODEL: {GH_AI_MODEL}
    ports:
      - '3000:3000'
    networks:
      - public_network
      - private_network
  postgres:
    image: postgres:16
    container_name: recipe-search-postgres
    environment:
      DB_USERNAME: {DB_USERNAME}
      DB_PASSWORD: {DB_PASSWORD}
      DB_NAME: {DB_NAME}
      DB_PORT: {DB_PORT}
      DB_HOST: {DB_HOST}
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      -private_network
networks:
  public_network:
    driver: bridge
  private_network:
    driver: bridge